### ISSUE TITLE
Contributing etc...

### ISSUE THREAD

**Issue by DavidWMerrill** [Zimbra-Community/Zimbra-Community.github.io#1]
Hi Cine,

New to github, I made a fork of this (thinking I'd eventually contribute!), rather than going to far with adding *anything* wanted to check with you on a framework for doing so. :)

How organized are things going to get?

Hope I'm not adding too much noise to your plate...

Thanks,
David

**Comment by mrCine** [comment]
Hey David!

GitHub Pages is entirely based on the [Jekyll framework](https://jekyllrb.com), and I've got my eyes on a [nice solution to write articles in Asciidoc](https://github.com/asciidoctor/jekyll-asciidoc-quickstart) that also automates the deployment process so that contribuiting will be as easy as opening a Pull Request on a specific with very few baseline requirements (content written in Asciidoc or Markdown, file naming following the standard Jekiyll guidelines).

Still testing all the automations, as soon as everything is up and running I will write a guide about how to contribute and get in touch with Barry for the CSS/Theming part...

**Comment by DavidWMerrill** [comment]
OK, got it. Thanks!
